// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onVentSwChange();
void onWindowSwChange();
void onCurrHumidityChange();
void onThermTempChange();
void onHeatingScheduleChange();

CloudSwitch ventSw;
CloudSwitch windowSw;
int currHumidity;
int currTemp;
int thermTemp;
int waterLevel;
CloudSchedule heatingSchedule;
bool heatingStatus;

void initProperties(){

  ArduinoCloud.addProperty(ventSw, READWRITE, 1 * SECONDS, onVentSwChange);
  ArduinoCloud.addProperty(windowSw, READWRITE, 1 * SECONDS, onWindowSwChange);
  ArduinoCloud.addProperty(currHumidity, READWRITE, 60 * SECONDS, onCurrHumidityChange);
  ArduinoCloud.addProperty(currTemp, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(thermTemp, READWRITE, 2 * SECONDS, onThermTempChange);
  ArduinoCloud.addProperty(waterLevel, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(heatingSchedule, READWRITE, 60 * SECONDS, onHeatingScheduleChange);
  ArduinoCloud.addProperty(heatingStatus, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
